### ISSUE TITLE
PIXEL 4A 5G China CMCC can not use VOLTE

### ISSUE THREAD

**Issue by feibing520** [swangjang/Pixel-Redbull-Carrier-Patch#1]
I used an other module (https://github.com/ender-zhao/Pixel-5-operator-network-unlock) before, 5G&VOLTE was functional,but there was some other issues, and the project is stop now.
So I tried this module 0.4 both A/B, 0.3A,can connect 5G, but can not get VOLTE work.Can u fix it or it is my problem?
THX for your work.

**Comment by swangjang** [comment]
Hi, sorry for the late response.
I'm still trying to figure out the VoLTE part but I currently don't know how to fix it.
I'll update the github when I find a working method.
Thanks 🙂

________________________________
From: feibing520 ***@***.***>
Sent: Tuesday, June 1, 2021 2:24 PM
To: swangjang/Pixel-Redbull-Carrier-Patch ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [swangjang/Pixel-Redbull-Carrier-Patch] PIXEL 4A 5G China CMCC can not use VOLTE (#1)


I used an other module (https://github.com/ender-zhao/Pixel-5-operator-network-unlock) before, 5G&VOLTE was functional,but there was some other issues, and the project is stop now.
So I tried this module 0.4 both A/B, 0.3A,can connect 5G, but can not get VOLTE work.Can u fix it or it is my problem?
THX for your work.

**Comment by feibing520** [comment]
That't OK, THX any way.
