### ISSUE TITLE
Pixel4a Android12 中国电信打电话的时候不能使用LTE，LTE的时候不能打电话，是不是我这边设置有问题？

### ISSUE THREAD

**Issue by AdrianHyj** [swangjang/Pixel-Redbull-Carrier-Patch#5]

**Comment by scudfly** [comment]
我Pixel5也是这个现象，我用这个模块可以正常使用
https://github.com/ender-zhao/Pixel-5-operator-network-unlock

**Comment by leebo219** [comment]
I use 0.4B with China Telecom, Volte is working by using https://github.com/edgd1er/voenabler However, 0.4B doesn't unlock 5g network, I only got 4g network.

**Comment by AdrianHyj** [comment]
加一些QQ群吧，我之前就是用QQ群友里面的一个包解决所有问题的
